name: Check for Nextcloud Base Image Update

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:

permissions:
  contents: write  # Needed to push updated digest to the repo

jobs:
  check-nextcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Get latest image digest
        id: digest
        run: |
          echo "digest=$(skopeo inspect docker://docker.io/library/nextcloud:production --format '{{.Digest}}')" >> $GITHUB_OUTPUT

      - name: Compare with stored digest
        id: check
        run: |
          DIGEST_FILE=".nextcloud_base_digest"
          NEW_DIGEST="${{ steps.digest.outputs.digest }}"
          echo "New digest: $NEW_DIGEST"
      
          if [ -f "$DIGEST_FILE" ]; then
            OLD_DIGEST=$(cat "$DIGEST_FILE")
          else
            OLD_DIGEST=""
          fi
      
          echo "Old digest: $OLD_DIGEST"
      
          if [ "$OLD_DIGEST" != "$NEW_DIGEST" ]; then
            echo "$NEW_DIGEST" > "$DIGEST_FILE"
            echo "Digest updated!"
            echo "updated=true" >> $GITHUB_ENV
          else
            echo "No update needed."
            echo "updated=false" >> $GITHUB_ENV
          fi

      - name: Upload new digest as artifact
        if: env.updated == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: nextcloud-base-digest
          path: .nextcloud_base_digest
          include-hidden-files: true

      - name: Commit and push updated digest to repo
        if: env.updated == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .nextcloud_base_digest
          git commit -m "Update stored base image digest"
          git push
