name: Check for Nextcloud Base Image Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  check-nextcloud:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.check.outputs.updated }}

    steps:
      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo

      - name: Get latest image digest
        id: digest
        run: |
          echo "digest=$(skopeo inspect docker://docker.io/library/nextcloud:production --format '{{.Digest}}')" >> $GITHUB_OUTPUT

      - name: Compare to previous
        id: check
        run: |
          DIGEST_FILE=.nextcloud_base_digest
          NEW_DIGEST="${{ steps.digest.outputs.digest }}"
          echo "New digest: $NEW_DIGEST"

          PREV_DIGEST=$(cat $DIGEST_FILE 2>/dev/null || echo "")
          echo "Previous digest: $PREV_DIGEST"

          if [[ "$PREV_DIGEST" != "$NEW_DIGEST" ]]; then
            echo "Digest updated!"
            echo "$NEW_DIGEST" > $DIGEST_FILE
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "No update needed"
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload digest file if updated
        if: steps.check.outputs.updated == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: updated-digest
          path: .nextcloud_base_digest
