name: Build Docker Image if Nextcloud Base Updated

on:
  workflow_run:
    workflows: ["Check for Nextcloud Base Image Update"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build-if-updated:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'push'

    permissions:
      actions: read   # Needed to download artifacts
      contents: read

    steps:
      - name: Try to download digest artifact (workflow_run only)
        if: github.event_name == 'workflow_run'
        uses: actions/download-artifact@v4
        with:
          name: nextcloud-base-digest
          path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
        continue-on-error: true

      - name: Check if digest artifact exists
        id: check
        run: |
          if [[ -f .nextcloud_base_digest ]]; then
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if no update detected (on workflow_run)
        if: github.event_name == 'workflow_run' && steps.check.outputs.updated == 'false'
        run: |
          echo "No Nextcloud base image update. Skipping build."
          exit 0

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$password" | docker login -u "$username" --password-stdin

      - name: Build the Docker image
        run: |
          docker build . -f Dockerfile -t hackermb/nextcloud-pdlib-dlib:latest

      - name: Push the Docker image
        run: |
          docker push hackermb/nextcloud-pdlib-dlib:latest
